/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is generated by TanStack Router and committed for fresh-clone type checks.

import { Route as rootRouteImport } from './app/__root';
import { Route as indexRouteImport } from './app/index';

const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof indexRoute;
}

export interface FileRoutesByTo {
  '/': typeof indexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof indexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/';
  id: '__root__' | '/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = { indexRoute };
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
